trigger:
- dotsource_azdevops_invokebuild
resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- powershell: |
    .\build.ps1 -InstallDependencies:$true -verbose -tasks 'setEnvironment','build','test','deploy'
  displayName: 'PowerShell - Build > test > deploy'
  env:
    psgallerykey: $(psgallerykey)
- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  inputs:
    testResultsFormat: NUnit