resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- powershell: |
   # Write your powershell commands here.
   Write-Host "Hello World"
   # Use the environment variables input below to pass secret variables to this script.
  displayName: 'PowerShell Script'