resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- powershell: ./ '.\DoTests.ps1'
  displayName: 'PowerShell Script'
- task: MyPowerShell
  inputs:
    targetType: 'inline'
    script: '# Write your powershell commands here.
Write-Host "Hello AzureDevOps! :)"
Write-Host "Hello World"
# Use the environment variables input below to pass secret variables to this script.'