trigger:
  branches:
    include:
    - 'dotsource_azdevops_invokebuild'
resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
# - powershell: |
#    # Install pester
#    Install-module -name Pester -scope currentuser -force -verbose

#    # Run Pester
#    Invoke-Pester -Path ".\Tests" -OutputFormat NUnitXml -OutputFile Test-Results.xml -PassThru

#    # Upload result
#    Write-Host "https://dev.azure.com/lazywinadmin/PSModuleSample/_apis/test/Runs/$BUILD_BUILDID/results?api-version=5.0"
#    [void]((New-Object 'System.Net.WebClient').UploadFile("https://dev.azure.com/lazywinadmin/PSModuleSample/_apis/test/Runs/$($env:BUILD_BUILDID)/results?api-version=5.0", (Resolve-Path .\Test-Results.xml)))

#    # List environment variables
#    gci env:\

#  displayName: 'PowerShell - Pester'
- powershell: |
    gci env:/
  displayName: 'PowerShell - List env variables'
#- powershell: |
#    (invoke-restmethod -method Get -URI "https://www.powershellgallery.com/api/v2/Search()?`$filter=(startswith(Id,'adsips') and IsLatestVersion)").properties.version
#  displayName: 'PowerShell - Get latest version'

#- task: PowerShell@2
#  displayName: 'PowerShell - Start build'
#  inputs:
#    filePath: 'build.ps1'
#  env:
#    psgallerykey: $(psgallerykey)

- powershell: |
    gci env:/
  displayName: 'PowerShell - List env variables'
- powershell: |
    .\build.ps1 -InstallDependencies
  env:
    psgallerykey: $(psgallerykey)
  displayName: 'PowerShell - Start Build'
- task: PublishTestResults@2
  displayName: 'Publish Test Results **/TEST-*.xml'
  inputs:
    testResultsFormat: NUnit