resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
#- powershell: ./ '.\DoTests.ps1'
#  displayName: 'PowerShell Script'
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '#test
$psversiontable'