resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- powershell: ./ '.\DoTests.ps1'
  displayName: 'PowerShell Script'

- task: ArchiveFiles@2
  displayName: 'Archive $(Build.BinariesDirectory)'

trigger:
  paths:
    exclude:
    - README.md
- task: PowerShell@2
  inputs:
    targetType: 'inline'
- task: AzurePowerShell@4
  inputs:
    ScriptType: 'InlineScript'
    Inline: '# hhhh
# You can write your azure powershell scripts inline here. 
Write-Host 
# You can also pass predefined and custom variables to this script using arguments'
    TargetAzurePs: 'LatestVersion'