resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: '# Write your powershell commands here.
Write-Host "Hello"
Write-Host "Hello World"

# Use the environment variables input below to pass secret variables to this script.'